# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import methods_pb2 as methods__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in methods_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PassStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddProteinBatch = channel.unary_unary(
                '/grpc.Pass/AddProteinBatch',
                request_serializer=methods__pb2.ProteinBatch.SerializeToString,
                response_deserializer=methods__pb2.Ack.FromString,
                _registered_method=True)
        self.CalculateBestMatches = channel.unary_stream(
                '/grpc.Pass/CalculateBestMatches',
                request_serializer=methods__pb2.Empty.SerializeToString,
                response_deserializer=methods__pb2.MatchResult.FromString,
                _registered_method=True)
        self.CalculateAllPairs = channel.unary_stream(
                '/grpc.Pass/CalculateAllPairs',
                request_serializer=methods__pb2.Empty.SerializeToString,
                response_deserializer=methods__pb2.MatchResult.FromString,
                _registered_method=True)
        self.DeleteProteins = channel.unary_unary(
                '/grpc.Pass/DeleteProteins',
                request_serializer=methods__pb2.EntryList.SerializeToString,
                response_deserializer=methods__pb2.Ack.FromString,
                _registered_method=True)
        self.RecalculateBestMatches = channel.unary_unary(
                '/grpc.Pass/RecalculateBestMatches',
                request_serializer=methods__pb2.Empty.SerializeToString,
                response_deserializer=methods__pb2.Ack.FromString,
                _registered_method=True)
        self.SaveState = channel.unary_unary(
                '/grpc.Pass/SaveState',
                request_serializer=methods__pb2.SaveStateRequest.SerializeToString,
                response_deserializer=methods__pb2.Ack.FromString,
                _registered_method=True)
        self.RollbackToState = channel.unary_unary(
                '/grpc.Pass/RollbackToState',
                request_serializer=methods__pb2.RollbackRequest.SerializeToString,
                response_deserializer=methods__pb2.Ack.FromString,
                _registered_method=True)
        self.GetSavedStates = channel.unary_unary(
                '/grpc.Pass/GetSavedStates',
                request_serializer=methods__pb2.Empty.SerializeToString,
                response_deserializer=methods__pb2.StateList.FromString,
                _registered_method=True)
        self.RemoveSavedState = channel.unary_unary(
                '/grpc.Pass/RemoveSavedState',
                request_serializer=methods__pb2.StateName.SerializeToString,
                response_deserializer=methods__pb2.Ack.FromString,
                _registered_method=True)


class PassServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddProteinBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateBestMatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateAllPairs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProteins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecalculateBestMatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackToState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSavedStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSavedState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PassServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddProteinBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProteinBatch,
                    request_deserializer=methods__pb2.ProteinBatch.FromString,
                    response_serializer=methods__pb2.Ack.SerializeToString,
            ),
            'CalculateBestMatches': grpc.unary_stream_rpc_method_handler(
                    servicer.CalculateBestMatches,
                    request_deserializer=methods__pb2.Empty.FromString,
                    response_serializer=methods__pb2.MatchResult.SerializeToString,
            ),
            'CalculateAllPairs': grpc.unary_stream_rpc_method_handler(
                    servicer.CalculateAllPairs,
                    request_deserializer=methods__pb2.Empty.FromString,
                    response_serializer=methods__pb2.MatchResult.SerializeToString,
            ),
            'DeleteProteins': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProteins,
                    request_deserializer=methods__pb2.EntryList.FromString,
                    response_serializer=methods__pb2.Ack.SerializeToString,
            ),
            'RecalculateBestMatches': grpc.unary_unary_rpc_method_handler(
                    servicer.RecalculateBestMatches,
                    request_deserializer=methods__pb2.Empty.FromString,
                    response_serializer=methods__pb2.Ack.SerializeToString,
            ),
            'SaveState': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveState,
                    request_deserializer=methods__pb2.SaveStateRequest.FromString,
                    response_serializer=methods__pb2.Ack.SerializeToString,
            ),
            'RollbackToState': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackToState,
                    request_deserializer=methods__pb2.RollbackRequest.FromString,
                    response_serializer=methods__pb2.Ack.SerializeToString,
            ),
            'GetSavedStates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSavedStates,
                    request_deserializer=methods__pb2.Empty.FromString,
                    response_serializer=methods__pb2.StateList.SerializeToString,
            ),
            'RemoveSavedState': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSavedState,
                    request_deserializer=methods__pb2.StateName.FromString,
                    response_serializer=methods__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Pass', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.Pass', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pass(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddProteinBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Pass/AddProteinBatch',
            methods__pb2.ProteinBatch.SerializeToString,
            methods__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateBestMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc.Pass/CalculateBestMatches',
            methods__pb2.Empty.SerializeToString,
            methods__pb2.MatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateAllPairs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc.Pass/CalculateAllPairs',
            methods__pb2.Empty.SerializeToString,
            methods__pb2.MatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProteins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Pass/DeleteProteins',
            methods__pb2.EntryList.SerializeToString,
            methods__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecalculateBestMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Pass/RecalculateBestMatches',
            methods__pb2.Empty.SerializeToString,
            methods__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Pass/SaveState',
            methods__pb2.SaveStateRequest.SerializeToString,
            methods__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackToState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Pass/RollbackToState',
            methods__pb2.RollbackRequest.SerializeToString,
            methods__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSavedStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Pass/GetSavedStates',
            methods__pb2.Empty.SerializeToString,
            methods__pb2.StateList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSavedState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Pass/RemoveSavedState',
            methods__pb2.StateName.SerializeToString,
            methods__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
